### ISSUE TITLE
Please update Cardiff club details

### ISSUE THREAD

**Issue by tullis** [UnionOfUKUnicyclists/unionofukunicyclists.github.io#7]
Hello,
I've submitted a pull request with updated details for the Cardiff unicycle hockey team.

If you could merge and deploy it, I'd be grateful.
Thanks.

**Comment by delcypher** [comment]
This was merged a while back but I forgot to close this issue.

**Comment by tullis** [comment]
:+1:

On 23 November 2017 09:50:52 GMT+00:00, Dan Liew <notifications@github.com> wrote:
>This was merged a while back but I forgot to close this issue.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/UnionOfUKUnicyclists/unionofukunicyclists.github.io/issues/7#issuecomment-346572256

--
